name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Live Squad Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project 2
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/IamDum/NationalBank/projects/2'
        column_name: 'Backlog'
    - name: Add Label
      uses: actions-ecosystem/action-add-labels@v1
      if: ${{ startsWith(github.event.comment.body, '/add-labels') }}
      with:
        labels: bugy
  
